splitter:
  root: examples/DATA_SPLITS/
  class_name: pydgn.data.splitter.LinkPredictionSingleGraphSplitter  # uses a bootstrapping technique
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: True
    inner_val_ratio: 0.05
    outer_val_ratio: 0.05
    test_ratio: 0.1  # in this case test_ratio will always be used and will apply to the number of total edges
    undirected: True  # we need to know if the graph is undirected or not to create proper random splits
    avoid_opposite_negative_edges: True  # Useful for losses/scores that consider the direction. Has an effect when the graph is directed.
dataset:
  root: DATA/
  class_name: pydgn.data.dataset.PlanetoidDatasetInterface
  args:
    root: DATA/
    name: cora
    split: full  # we will split the full graph according to the edges, not according to classes
